services:
  api:
    build: ./
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8004:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/shopping
      - DATABASE_TEST_URL=postgresql://postgres:postgres@database:5432/shopping_test
      - ENABLE_METRICS=true
    depends_on:
    - database

  database:
    build:
      context: src/database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopping
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
       - ./data:/var/lib/postgresql/data
